{
  "openapi": "3.0.0",
  "info": {
    "title": "litc",
    "description": "",
    "contact": {},
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://127.0.0.1:5000/api",
      "variables": {}
    }
  ],
  "paths": {
    "/product": {
      "get": {
        "tags": [
          "Misc"
        ],
        "summary": "List All products",
        "description": "",
        "operationId": "ListAllproducts",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "put": {
        "tags": [
          "Misc"
        ],
        "summary": "Edit product",
        "description": "",
        "operationId": "Editproduct",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/EditproductRequest"
                  },
                  {
                    "example": {
                      "name": "Test2",
                      "brand": "lrele",
                      "calories": 10,
                      "sugar_percentage": 54,
                      "saturated_fats_percentage": 55
                    }
                  }
                ]
              },
              "example": {
                "name": "Test2",
                "brand": "lrele",
                "calories": 10,
                "sugar_percentage": 54,
                "saturated_fats_percentage": 55
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "post": {
        "tags": [
          "Misc"
        ],
        "summary": "Create product",
        "description": "",
        "operationId": "Createproduct",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/CreateproductRequest"
                  },
                  {
                    "example": {
                      "name": "Tomate",
                      "brand": "Hacendado",
                      "calories": 10,
                      "sugar_percentage": 54,
                      "saturated_fats_percentage": 54
                    }
                  }
                ]
              },
              "example": {
                "name": "Tomate",
                "brand": "Hacendado",
                "calories": 10,
                "sugar_percentage": 54,
                "saturated_fats_percentage": 54
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/docs/": {
      "get": {
        "tags": [
          "Misc"
        ],
        "summary": "API Doc",
        "description": "",
        "operationId": "APIDoc",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/market": {
      "get": {
        "tags": [
          "Misc"
        ],
        "summary": "List All markets",
        "description": "",
        "operationId": "ListAllmarkets",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "post": {
        "tags": [
          "Misc"
        ],
        "summary": "Create market",
        "description": "",
        "operationId": "Createmarket",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/CreatemarketRequest"
                  },
                  {
                    "example": {
                      "name": "mercadona",
                      "address": "address",
                      "opening_time": "9:00",
                      "closing_time": "9:00"
                    }
                  }
                ]
              },
              "example": {
                "name": "mercadona",
                "address": "address",
                "opening_time": "9:00",
                "closing_time": "9:00"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/product/assign_price": {
      "post": {
        "tags": [
          "Misc"
        ],
        "summary": "Create product1",
        "description": "",
        "operationId": "Createproduct1",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/CreateproductRequest1"
                  },
                  {
                    "example": {
                      "market": "mercadona",
                      "brand": "lrele",
                      "product": "Test2",
                      "price": 4
                    }
                  }
                ]
              },
              "example": {
                "market": "mercadona",
                "brand": "lrele",
                "product": "Test2",
                "price": 4
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    }
  },
  "components": {
    "schemas": {
      "EditproductRequest": {
        "title": "EditproductRequest",
        "required": [
          "name",
          "brand",
          "calories",
          "sugar_percentage",
          "saturated_fats_percentage"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "brand": {
            "type": "string"
          },
          "calories": {
            "type": "integer",
            "format": "int32"
          },
          "sugar_percentage": {
            "type": "integer",
            "format": "int32"
          },
          "saturated_fats_percentage": {
            "type": "integer",
            "format": "int32"
          }
        },
        "example": {
          "name": "Test2",
          "brand": "lrele",
          "calories": 10,
          "sugar_percentage": 54,
          "saturated_fats_percentage": 55
        }
      },
      "CreatemarketRequest": {
        "title": "CreatemarketRequest",
        "required": [
          "name",
          "address",
          "opening_time",
          "closing_time"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "opening_time": {
            "type": "string"
          },
          "closing_time": {
            "type": "string"
          }
        },
        "example": {
          "name": "mercadona",
          "address": "address",
          "opening_time": "9:00",
          "closing_time": "9:00"
        }
      },
      "CreateproductRequest": {
        "title": "CreateproductRequest",
        "required": [
          "name",
          "brand",
          "calories",
          "sugar_percentage",
          "saturated_fats_percentage"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "brand": {
            "type": "string"
          },
          "calories": {
            "type": "integer",
            "format": "int32"
          },
          "sugar_percentage": {
            "type": "integer",
            "format": "int32"
          },
          "saturated_fats_percentage": {
            "type": "integer",
            "format": "int32"
          }
        },
        "example": {
          "name": "Tomate",
          "brand": "Hacendado",
          "calories": 10,
          "sugar_percentage": 54,
          "saturated_fats_percentage": 54
        }
      },
      "CreateproductRequest1": {
        "title": "CreateproductRequest1",
        "required": [
          "market",
          "brand",
          "product",
          "price"
        ],
        "type": "object",
        "properties": {
          "market": {
            "type": "string"
          },
          "brand": {
            "type": "string"
          },
          "product": {
            "type": "string"
          },
          "price": {
            "type": "integer",
            "format": "int32"
          }
        },
        "example": {
          "market": "mercadona",
          "brand": "lrele",
          "product": "Test2",
          "price": 4
        }
      }
    }
  },
  "tags": [
    {
      "name": "Misc",
      "description": ""
    }
  ]
}